spring:
  application:
    name: discovery-service

eureka:
  instance:
    # docker?? ??? ??? ??? ?? localhost? ??? host.docker.internal??? ??.
    hostname: host.docker.internal
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
  address: 0.0.0.0
